#!/bin/sh

## SHORTCUT

alias bc='bc --mathlib'
alias chgrp='chgrp --preserve-root'
alias chmod='chmod --preserve-root'
alias chown='chown --preserve-root'
alias diff='diff --recursive --side-by-side --ignore-all-space'
alias mkdir='mkdir --parents --verbose'
alias mount='mount | column --table'
alias wget='wget --continue'

## SHORTENED

alias d='rm -I --preserve-root'
alias e='$EDITOR'
alias h='history | less'
alias j='jobs -l'
alias k='kubectl'
alias l='ls -l'
alias m='mv'

## MAIN

alias sha1='openssl sha1'

alias cpuinfo='lscpu'
alias meminfo='free -m -l -t'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
alias pscpu='ps auxf | sort -nr -k 3'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias psmem='ps auxf | sort -nr -k 4'

alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'

alias pbcopy="xclip -selection c"
alias pbpaste="xclip -selection c -o"

# apt
if type apt-get >/dev/null 2>&1; then
  alias apt-get="sudo apt-get"
  alias update='sudo apt-get update && sudo apt-get dist-upgrade --yes && apt-get autoremove --yes && apt-get autoclean'
fi

# docker
if type docker >/dev/null 2>&1; then
  alias dr="docker run --interactive --tty --rm"

  alias dive="dr -v /var/run/docker.sock:/var/run/docker.sock cgr.dev/chainguard/dive"
  # alias k9s="docker run --rm -it -v $KUBECONFIG:/root/.kube/config quay.io/derailed/k9s"
  alias dokuwiki='xdg-open http://127.0.0.1:80 && docker run --rm -p 80:8080 -v /home/$HOME/wiki/:/storage dokuwiki/dokuwiki:stable'

  # docker compose
  alias phpstan="docker compose exec php './vendor/bin/phpstan' analyze"
fi

# ffmpeg
if type ffmpeg >/dev/null 2>&1; then
  alias record_webcam='ffplay -f v4l2 -vf "hflip,format=yuv420p" -video_size 480x320 -i /dev/video0'
  alias record_screen0='ffplay -f x11grab -video_size 1920x1080 -framerate 25 -i :0.0'
  alias record_screen1='ffplay -f x11grab -video_size 1920x1080 -framerate 25 -i :0.0+1920,0'
  alias record_screen_all='ffplay -framerate 25 -f x11grab -i :0.0'
  alias screenshot_0='ffmpeg -f x11grab -video_size 1920x1080 -framerate 1 -i :0.0 -vframes 1'
  alias screenshot_1='ffmpeg -f x11grab -video_size 1920x1080 -framerate 1 -i :0.0+1920,0 -vframes 1'
  alias screenshot_all='ffmpeg -f x11grab -framerate 1 -i :0.0 -vframes 1'
fi

# iptables
alias iplist='sudo iptables -L -vn --line-numbers'

# kitty
if [ "${TERM}" = 'xterm-kitty' ]; then
  alias diff='kitten diff'
  alias emoji='kitten unicode-input'
  alias icat='kitten icat'
  alias notify-send='kitten notify'
  alias ssh='kitten ssh'
  alias pbcopy="kitten clipboard"
  alias pbpaste="xclip -selection c -o"
fi

# kubectl
if type kubectl >/dev/null 2>&1; then
  alias kg='kubectl get'
  alias kl='kubectl logs'
  alias ke='kubectl edit'
  alias kd='kubectl describe'
  alias kdd='kubectl delete'
  alias kgp='kubectl get pods'
  alias kgd='kubectl get deployments'
  alias wkgp='watch kubectl get pod'

  alias kscript='__kubectl_exec_script'
  alias kshell='__kubectl_exec_shell'
  alias kweb='__kubectl_open_web'

  alias kfind='kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found'

  # kubectx
  # shellcheck disable=SC2154
  alias kubectx='__ctx__="$(kubectl config get-contexts --output name | fzf)"; [ -z "${__ctx__}" ] || kubectl config use-context "${__ctx__}"'
  alias kcx='kubectx'
  alias kprod='kubectl config use-context gke_sportello-telematico_europe-west1-b_stu3-prod'
  alias kstag='kubectl config use-context gke_sportello-telematico-dev_europe-west1-b_staging'

  # kubens
  # shellcheck disable=SC2154
  alias kubens='__ns__="$(kubectl get namespaces --no-headers --output custom-columns=name:{.metadata.name} | fzf)"; [ -z "${__ns__}" ] || kubectl config set-context --current --namespace "${__ns__}"'
  alias kns='kubens'
fi

## APPS

type codium >/dev/null 2>&1 && alias code='codium'

## X11

alias xreload='xrdb -load ~/.config/X11/Xresources'

## Private

# bookmarks

alias b='bookmarks'
alias bo='bookmark_open'
alias by='bookmark_copy'

# quick actions

alias qa='quick_action'

# projects

alias p='projects'
alias po='project_open'
alias py='project_copy'
