#!/bin/sh

# Variables
#shellcheck source=/dev/null
[ -f "${HOME}/.config/sh/variables" ] && . "${HOME}/.config/sh/variables"

# Aliases
#shellcheck source=/dev/null
[ -f "${HOME}/.config/sh/aliases" ] && . "${HOME}/.config/sh/aliases"

# External sources
#shellcheck source=/dev/null
[ -f "${HOME}/.config/sh/sources" ] && . "${HOME}/.config/sh/sources"

# Functions
#shellcheck source=/dev/null
[ -f "${HOME}/.config/sh/functions" ] && . "${HOME}/.config/sh/functions"

# Completion
#shellcheck source=/dev/null
[ -f "${HOME}/.config/sh/completion" ] && . "${HOME}/.config/sh/completion"

# Private
#shellcheck source=/dev/null
[ -f "${HOME}/.config/private/shrc" ] && . "${HOME}/.config/private/shrc"
