#!/bin/sh

files="""
${HOME}/.config/envman/PATH.env
${HOME}/.config/envman/load.sh
${HOME}/.config/private/aliases
${HOME}/.config/private/functions
${HOME}/.config/private/quick_action
${HOME}/.config/private/shrc
${HOME}/.fzf.bash
"""

# shellcheck disable=SC2034
printf '%s' "${files}" \
  | sed '/^\s*$/d' \
  | while IFS='' read -r file; do
    [ -s "${file}" ] || continue

    # shellcheck source=/dev/null
    if ! . "${file}" >/dev/null 2>&1; then
      printf "[ERROR] Could not source file %s for %s, message:\n%s\n" "${file}" "${app}" "${?}"
      continue
    fi
  done
