#!/bin/sh

# defaults
BROWSER="$(which firefox)"
export BROWSER

EDITOR="$(which vi)"
export EDITOR

PAGER="$(which less)"
export PAGER

VISUAL="$(which vi)"
export VISUAL

# bash
export PATH="${PATH}:${HOME}/.config/sh/script"

# borg
# export BORG_PASSCOMMAND='gpg --decrypt borg-passphrase.gpg'
# export BORG_PASSPHRASE='my super secret passphrase'
# export PATH="${PATH}:${HOME}/.config/borg/script"

# cd
export CDPATH=""

# elinks
# export ELINKS_CONFDIR="${HOME}/.config/elinks"

# emacs
# export PATH="${PATH}:${HOME}/.config/emacs/bin"

# fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden --no-ignore'
export FZF_DEFAULT_OPTS="--height=40% --layout=reverse --info=inline --border --margin=1 --padding=1"

# kubectl
K9S_EDITOR=${EDITOR:-vi}
KUBECONFIG="${HOME}/.kube/config"
KUBECTX_CURRENT_BGCOLOR="$(tput setab 7)" # white background
KUBECTX_CURRENT_FGCOLOR="$(tput setaf 6)" # blue text

export K9S_EDITOR
export KUBECONFIG
export KUBECTX_CURRENT_BGCOLOR
export KUBECTX_CURRENT_FGCOLOR

# nvm
NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
export NVM_DIR

# tmux
export TMUX_TMPDIR="${HOME}/.local/state"

# w3m
export W3M_DIR="${HOME}/.config/w3m"
export WWW_HOME='https://lite.duckduckgo.com/lite'

# wireshark
export WIRESHARK_CONFIG_DIR="${HOME}/.config/wireshark"

# x11
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
