#!/usr/bin/zsh

export P10KPROMPT="${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
[[ ! -f $P10KPROMPT ]] || source $P10KPROMPT

export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="$HOME/.config/zsh/"

ZSH_THEME="powerlevel10k/powerlevel10k"

zstyle ':omz:update' mode auto      # update automatically without asking

source ~/.zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh

plugins=(
  fzf
  git
  kube-ps1
  nmap
  zsh-interactive-cd
  zsh-navigation-tools
)

source $ZSH/oh-my-zsh.sh

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# K9s
PROMPT=$PROMPT'$(kube_ps1) '

# Python
if whence pip &>/dev/null; then
  source <(pip completion --zsh)
fi

# Kubectl
if whence kubectl &>/dev/null; then
  source <(kubectl completion zsh)
  alias k='kubectl'
  complete -F __start_kubectl k
fi

# Helm
if whence helm &>/dev/null; then
  source <(helm completion zsh)
fi

# Kind
if whence kind &>/dev/null; then
  source <(kind completion zsh)
fi

[[ ! -f ~/.zsh_aliases ]] || source ~/.zsh_aliases
