BRANCH="$(git branch --show-current)"

# PS1 attuale
export $PS1="\[\033[0;32m\]@\u \[\033[0m\]➜ \[\033[1;34m\]\w \[\033[0;36m\](\[\033[1;31m\]$BRANCH\[\033[0;36m\]) \[\033[0m\]\$ "

# Meta PS1
PROMPT_COMMAND='PS1_CMD1=$($(git branch 2>/dev/null | grep '"'"'*'"'"' | colrm 1 2))'; PS1='\u@\h | (${PS1_CMD1}) \w \r\n\\_ '
